name: LLL_Release

on:
  push:
    branches:
      - '**'
      - '!min'

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pull-requests: write

    steps:      
      - name: Checkout min branch
        uses: actions/checkout@v3
        with:
          ref: main
          submodules: recursive
          
      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:2.0.0
        with:
          add_suffix: false     # Optional

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://lll.pj568.eu.org/

      - name: Output sitemap stats
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
          echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: min # The branch the action should deploy to.
          folder: . # The folder the action should deploy.

      - name: Ping Google
        run: curl https://www.google.com/ping?sitemap=https://LLL.PJ568.eu.org/sitemap.xml
